version: "3.8"

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" # <-- Add this line
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=mnik414@gmail.com"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http"
      - "--log.level=INFO"
      - "--log.filePath=/logs/traefik.log"
      - "--accessLog.filePath=/logs/access.log"
      - "--accessLog.bufferingSize=100"
      - "--providers.swarm=true"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080 # <-- Expose port 8080 for dashboard
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - "logs:/logs"

  tileserver:
    image: maptiler/tileserver-gl
    volumes:
      - ./data/tiles:/data
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # define Server-Port
        - "traefik.http.services.tiles-meydoon.loadbalancer.server.port=8080"
        # define Middlewares
        - "traefik.http.middlewares.tiles-to-https-meydoon.redirectscheme.scheme=https"
        - "traefik.http.middlewares.tiles-to-https-meydoon.redirectscheme.permanent=true"
        # Redirect "host" HTTP traffic to HTTPS
        - "traefik.http.routers.tiles-http-meydoon.entrypoints=http"
        - "traefik.http.routers.tiles-http-meydoon.rule=Host(`tiles.meydoon.org`)"
        - "traefik.http.routers.tiles-http-meydoon.middlewares=tiles-to-https-meydoon"
        # Handle HTTPS
        - "traefik.http.routers.tiles-https-meydoon.entrypoints=https"
        - "traefik.http.routers.tiles-https-meydoon.rule=Host(`tiles.meydoon.org`)"
        - "traefik.http.routers.tiles-https-meydoon.tls=true"
        - "traefik.http.routers.tiles-https-meydoon.tls.certresolver=letsencrypt"
    ports:
      - "5004:8080"

volumes:
  letsencrypt:
  logs:
